import {
  addresses,
  defaultSliceChainId,
  getFundsModuleAddress,
  getProductsModuleAddress,
  getSliceCoreAddress,
  supportedSliceCheckoutChainIds
} from "@slice/indexer-shared"

const outputPath = new URL(
  "../src/execution/generated/commerceFacts.ts",
  import.meta.url
)
const check = process.argv.includes("--check")

const hookAddresses = Array.from(
  new Set(
    Object.values(addresses).flatMap((category) =>
      Object.values(category).flatMap((deployments) =>
        deployments.map(({ address }) => address.toLowerCase())
      )
    )
  )
).sort()

const deploymentFacts = Object.fromEntries(
  supportedSliceCheckoutChainIds.map((chainId) => [
    chainId,
    {
      fundsModule: getFundsModuleAddress(chainId),
      productsModule: getProductsModuleAddress(chainId),
      sliceCore: getSliceCoreAddress(chainId)
    }
  ])
)

const generated = `// Generated by scripts/generate-commerce-facts.ts. Do not edit.\nimport type { Address } from "viem"\n\nexport const defaultSliceChainId = ${defaultSliceChainId}\nexport const supportedSliceCheckoutChainIds = ${JSON.stringify(supportedSliceCheckoutChainIds)} as const\n\nconst commerceDeployments = ${JSON.stringify(deploymentFacts, null, 2)} as const\n\nconst generatedHookAddresses = new Set(${JSON.stringify(hookAddresses, null, 2)})\n\nconst getCommerceDeployment = (chainId: number) => {\n  const deploymentChainId = chainId === 31_337 ? 8_453 : chainId\n  const deployment = Object.entries(commerceDeployments).find(\n    ([candidate]) => Number(candidate) === deploymentChainId\n  )?.[1]\n  if (deployment === undefined) {\n    throw new Error(\`Slice commerce is not deployed on chain \${chainId}.\`)\n  }\n  return deployment\n}\n\nexport const getFundsModuleAddress = (chainId: number): Address =>\n  getCommerceDeployment(chainId).fundsModule\nexport const getProductsModuleAddress = (chainId: number): Address =>\n  getCommerceDeployment(chainId).productsModule\nexport const getSliceCoreAddress = (chainId: number): Address =>\n  getCommerceDeployment(chainId).sliceCore\nexport const isGeneratedHookAddress = (address: Address) =>\n  generatedHookAddresses.has(address.toLowerCase())\nexport const generatedHookAddressList = Array.from(generatedHookAddresses) as Address[]\n`

const current = await Bun.file(outputPath)
  .text()
  .catch(() => "")
if (check) {
  if (current !== generated) {
    console.error("Generated commerce facts are stale. Run generate:commerce.")
    process.exitCode = 1
  }
} else {
  await Bun.write(outputPath, generated)
}
